---
userSwapChoices:
    - none      # Create no swap, use no swap
    - small     # Create small swap partition (usually 256MB)
    - suspend   # Create swap partition at least as large as total physical RAM
    - file      # Create a swap file in the root file system.

drawNestedPartitions:   false
alwaysShowPartitionLabels: true
initialPartitioningChoice: none
initialSwapChoice: none
defaultFileSystemType:  "ext4"

enableLuksAutomatedPartitioning: true
luksGeneration: luks2
