---
modules-search: [ local ]

instances:
- id:       apps
  module:   netinstall
  config:   netinstall.yaml

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - netinstall@apps
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localenc
  - users
  - networkcfg
  - hwclock
  - services-systemd
  - packages
  - grubcfg
  - bootloader
  - umount
- show:
  - finished

brand: scopeos
